"""Pharma Research Assistant — Streamlit UI."""
import os
import re
from pathlib import Path

import streamlit as st
from dotenv import load_dotenv
from langchain_core.messages import AIMessage, HumanMessage

load_dotenv()

from chat.history import load_history, save_history, clear_history

# ---------------------------------------------------------------------------
# Page config — must be the FIRST st.* call
# ---------------------------------------------------------------------------
st.set_page_config(
    page_title="PharmaRA — Pharma Research Assistant",
    page_icon="🧬",
    layout="wide",
)

# ---------------------------------------------------------------------------
# Authentication
# ---------------------------------------------------------------------------
from auth.config import build_authenticator, login_gate

authenticator = build_authenticator()
user_role = login_gate(authenticator)  # stops page if not authenticated


def _extract_text(content) -> str:
    """Extract plain text from AIMessage content.

    Gemini thinking models return content as a list of typed blocks
    e.g. [{"type": "text", "text": "...", "extras": {"signature": "..."}}].
    This normalises both that format and plain strings to a single str.
    """
    if isinstance(content, list):
        return "\n".join(
            block["text"] for block in content
            if isinstance(block, dict) and block.get("type") == "text"
        )
    return content or ""


# ---------------------------------------------------------------------------
# Env check
# ---------------------------------------------------------------------------
if not os.getenv("OPENAI_API_KEY"):
    st.error(
        "**OPENAI_API_KEY not set.** Copy `.env.example` to `.env` and add your API key, "
        "then restart the app with `streamlit run app.py`."
    )
    st.stop()

# ---------------------------------------------------------------------------
# Load vectorstore + build graph (cached per mode — runs once per mode)
# ---------------------------------------------------------------------------
@st.cache_resource(show_spinner="Loading research library...")
def load_agent(mode: str = "classic"):
    from rag.vectorstore import load_index, load_wiki_index
    from agent.graph import build_graph
    try:
        vs = load_index()
    except Exception as e:
        return None, str(e)
    wiki_vs = None
    if mode == "wiki":
        try:
            wiki_vs = load_wiki_index()
        except Exception:
            pass  # wiki index not built yet — app will warn user
    graph = build_graph(vs, wiki_vs, mode)
    return graph, None


rag_mode = st.session_state.get("rag_mode", "classic")
graph, load_error = load_agent(rag_mode)

if load_error:
    st.error(
        f"**Could not connect to Redis vector index.**\n\n"
        f"Make sure Redis Stack is running on `{os.getenv('REDIS_URL', 'redis://localhost:26379')}` "
        f"and run:\n\n```bash\npython scripts/build_index.py\n```\n\nError: {load_error}"
    )
    st.stop()

# ---------------------------------------------------------------------------
# Sidebar
# ---------------------------------------------------------------------------
with st.sidebar:
    st.title("🧬 PharmaRA")
    st.caption("Pharmaceutical Research Assistant")

    username = st.session_state.get("username", "")
    st.caption(f"Logged in as **{username}** ({user_role})")
    try:
        authenticator.logout(button_name="Logout", location="sidebar")
    except Exception:
        pass
    if st.button("🗑️ Clear chat history", use_container_width=True):
        clear_history(username)
        st.session_state[_msg_key] = []
        st.session_state[_cite_key] = {}
        st.rerun()
    st.divider()

    st.markdown("### Retrieval Mode")
    st.radio(
        "Select retrieval strategy:",
        options=["classic", "wiki"],
        format_func=lambda x: "🔍 Classic RAG" if x == "classic" else "📖 Wiki RAG",
        key="rag_mode",
        help=(
            "**Classic RAG**: searches raw document chunks via vector similarity.\n\n"
            "**Wiki RAG**: searches pre-compiled wiki pages (summary + concepts + findings) "
            "generated by LLM at index time."
        ),
    )
    if rag_mode == "wiki" and graph is not None:
        # Warn if wiki vectorstore wasn't loaded (index not built yet)
        from agent.tools import _wiki_vectorstore
        if _wiki_vectorstore is None:
            st.warning(
                "⚠️ Wiki index not found. Run:\n```\npython scripts/build_index.py\n```"
            )
    st.divider()

    st.markdown("### About")
    st.markdown(
        "PharmaRA is an AI-powered assistant for pharmaceutical R&D teams. "
        "It combines **RAG over research papers**, **structured assay data queries**, "
        "and **external literature lookup** in a single conversational interface."
    )
    st.divider()

    st.markdown("### Example queries")
    examples = [
        "What are the IC50 values for EGFR inhibitors in the database?",
        "Summarize the key findings on EGFR T790M resistance mutations.",
        "Which compounds have selectivity ratio above 100?",
        "What is the clinical trial outcome for SAN-4891 in COPD?",
        "Show me lead compounds for CDK4/Cyclin D1.",
        "Fetch the README from https://github.com/deepmind/alphafold",
        "Look up papers on protein structure prediction with AlphaFold.",
    ]
    for ex in examples:
        if st.button(ex, use_container_width=True, key=ex):
            st.session_state.pending_input = ex

    st.divider()
    st.markdown("### Safety note")
    st.warning(
        "PharmaRA is for **research use only** and cannot provide medical advice. "
        "All queries requesting personal health guidance will be declined."
    )
    st.divider()
    model = os.getenv("MODEL_NAME", "gpt-4o-mini")
    st.caption(f"Model: `{model}` · Embeddings: `{os.getenv('EMBEDDING_MODEL', 'text-embedding-3-small')}`")

# Per-user session state keys so each account has its own isolated chat history
_msg_key = f"messages_{username}"
_cite_key = f"citations_{username}"

# ---------------------------------------------------------------------------
# Chat state (namespaced per user, backed by Redis)
# ---------------------------------------------------------------------------
if _msg_key not in st.session_state:
    msgs, cites = load_history(username)
    st.session_state[_msg_key] = msgs
    st.session_state[_cite_key] = cites

# ---------------------------------------------------------------------------
# Header
# ---------------------------------------------------------------------------
st.title("🧬 Pharma Research Assistant")
mode_label = "📖 Wiki RAG" if rag_mode == "wiki" else "🔍 Classic RAG"
st.caption(
    f"Ask about research findings, assay data, compounds, clinical trials, or external papers. "
    f"&nbsp;·&nbsp; Mode: **{mode_label}**"
)

# ---------------------------------------------------------------------------
# Display chat history
# ---------------------------------------------------------------------------
for i, msg in enumerate(st.session_state[_msg_key]):
    msg_role = "user" if isinstance(msg, HumanMessage) else "assistant"
    with st.chat_message(msg_role):
        st.markdown(_extract_text(msg.content))
        if msg_role == "assistant" and i in st.session_state[_cite_key]:
            cites = st.session_state[_cite_key][i]
            if cites:
                with st.expander(f"📄 Sources ({len(cites)})", expanded=False):
                    for c in cites:
                        st.markdown(f"- {c}")

# ---------------------------------------------------------------------------
# Input handling (sidebar button OR chat input)
# ---------------------------------------------------------------------------
pending = st.session_state.pop("pending_input", None)
user_input = pending or st.chat_input("Ask a research question...")

if user_input:
    with st.chat_message("user"):
        st.markdown(user_input)

    human_msg = HumanMessage(content=user_input)
    st.session_state[_msg_key].append(human_msg)

    with st.chat_message("assistant"):
        with st.spinner("Thinking..."):
            state_in = {"messages": st.session_state[_msg_key], "blocked": False}
            result = graph.invoke(state_in, config={"recursion_limit": 10})

        final_msgs = result["messages"]
        blocked = result.get("blocked", False)

        ai_reply = None
        for m in reversed(final_msgs):
            if isinstance(m, AIMessage) and not m.tool_calls:
                ai_reply = m
                break

        if ai_reply is None:
            ai_reply = AIMessage(content="No response generated.")

        reply_text = _extract_text(ai_reply.content)

        if blocked:
            st.error(reply_text)
        else:
            st.markdown(reply_text)

        cite_matches = re.findall(r"\[Source:\s*([^\]]+)\]", reply_text)
        citation_idx = len(st.session_state[_msg_key])

        if cite_matches and not blocked:
            with st.expander(f"📄 Sources ({len(set(cite_matches))})", expanded=False):
                for c in set(cite_matches):
                    st.markdown(f"- {c}")
            st.session_state[_cite_key][citation_idx] = list(set(cite_matches))

    st.session_state[_msg_key].append(ai_reply)
    save_history(username, st.session_state[_msg_key], st.session_state[_cite_key])
